### ISSUE TITLE
bug: About dialog doesn't respect new build numbers.

### ISSUE THREAD

**Issue by ajborka** [jfayre/talking-flight-monitor-net#10]
**Describe the bug**
When viewing the about dialog, the version number is supposed to change with every build. However, the version number still says 1.0.0.

**To Reproduce**
1. Launch the new version of TFM.
2. Activate the help>about... menu item.
3. Read the contents of the dialog that appears.
4. Load master branch into Visual Studio.
5. Look at the about dialog source code.

**Expected behavior**
The dialog's version number would change with each build.

**additional information
 - OS: Windows 10 prerelease (insider's build)
 - TFM version: Build directly from the master branch.
 - Flight simulator in use: n/a

**Additional context**
None

**Comment by jfayre** [comment]
The build numbers now get updated when appveyor builds them.
