### ISSUE TITLE
Extreme Lag When Tabbing Through the PMDG 737 CDU

### ISSUE THREAD

**Issue by trodick** [jfayre/talking-flight-monitor-net#100]
I don't know exactly how to explain this, but I have several seconds of lag as I tab around the FMC of the PMDG 737 in TFM. This makes it very slow to program the FMC, and I don't know of any strategies to fix it. I've got 20 GB RAM, quad-core (8-thread) Core i7, 1 TB SSD, latest version of P3d 4.5, and am using the latest Git head revision of TFM (commit 20FA42A7). My screen reader is NVDA 2020.4. Please advise.

**Comment by ajborka** [comment]
It might have something to do with the refresh method set on a 30 second timer. The routine attempts to preserve the current cursor location in the display. I don't experience any lag when tabbing around. When in your 737, try pressing ALT+ENTER to put the sim in full screen mode to see if the lag goes away.

**Comment by trodick** [comment]
I'll try that, but from a technical standpoint I'm curious how that would possibly help. Additionally, would increasing my swap file size help? I already have the sim graphics settings set on their lowest possible values.

**Comment by ajborka** [comment]
I had some other people test this problem. It seems to only happen on initial load of the PMDG aircraft. After that, everything seems to work as expected. What slight lag does exist can be gotten rid of by reloading TFM before starting your flight. An interesting note is that JAWS 2019 and later doesn't experience any lag.

**Comment by ajborka** [comment]
This appears to be an NVDA problem, not a TFM issue. However, we do have plans to try and optimize the CDU with NVDA. This is on the to-do list, so closing the issue.
