### ISSUE TITLE
feature request: airport positions dialogue

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#102]
Idea would be to have a hotkey to bring up, let us say, three lists in tab order: runways, taxiways/holding points, and gates. Pressing enter on one would move the aircraft to that position, as pulled from the makerunways file. We are not yet sure how much information can be pulled, and having an up-to-date scenery would be important especially for smaller airports which are not modelled as well by default. This would also give the pilot an overview of the size of the airport, number of gates, and length of taxi.

**Comment by ajborka** [comment]
Yes, this is entirely possible. We will work on it when time allows. At the moment, we are working on the PMDG 777 and based on results from new code, plan on refactoring the entire project to be in line with the new code.

**Comment by BviPilots** [comment]
Hi,
I think that is a cool idea. I would guess that as long as you have
everything updated, it would be good? Is this connected to the idea of
being able to taxy? Wasnt sure if that was part of it or not. Either
way i like this idea for sure. Keep up the great work guys.

**Comment by blindflightsimmer** [comment]
For the moment it’ll be something to help us find gates and runways to reposition, and more importantly to reposition to taxiways and runway holding points on vatsim until the full taxi system is in place so we don’t have to spawn right onto the runway without going to the holding points first. Sent from Mail for Windows 10 From: BviPilotsSent: 30 May 2021 20:17To: jfayre/talking-flight-monitor-netCc: blindflightsimmer; AuthorSubject: Re: [jfayre/talking-flight-monitor-net] feature request: airport positions dialogue (#102) Hi,I think that is a cool idea. I would guess that as long as you haveeverything updated, it would be good? Is this connected to the idea ofbeing able to taxy? Wasnt sure if that was part of it or not. Eitherway i like this idea for sure. Keep up the great work guys.On 5/30/21, Andy Borka ***@***.***> wrote:> Yes, this is entirely possible. We will work on it when time allows. At the> moment, we are working on the PMDG 777 and based on results from new code,> plan on refactoring the entire project to be in line with the new code.>> --> You are receiving this because you are subscribed to this thread.> Reply to this email directly or view it on GitHub:> https://github.com/jfayre/talking-flight-monitor-net/issues/102#issuecomment-851034365—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ajborka** [comment]
The original concept is part of the taxi idea. Hopefully we can provide a map of sorts. Each taxiway has segments, and each taxiway is connected to each other. So, we should be able to get you a routing, or at worst, see how ATC is going to route you once you get a taxi routing. We will see.

**Comment by ajborka** [comment]
This is possible for gates, runways, and airports. Unfortunately, it is not looking good for taxiways. Since runways/gates/airports are already in future plans, and taxiways are not possible yet, closing this issue. If/when taxiways become more usable, open another issue on that subject.
