### ISSUE TITLE
Incorrect Readings for Engine N1/N2 and Fuel Flow in PMDG 777

### ISSUE THREAD

**Issue by trodick** [jfayre/talking-flight-monitor-net#103]
When using the PMDG 777 with the latest TFM from master (commit 48A709F1), when you press ], Shift+1 for engine information or ], F for fuel flow, the information you get back is nonsensical. When the engines are not running, you get an engine N1 of 1, N2 of 16, and fuel flow of 37 PPH. If the engines are running, N1, N2, and fuel flow as reported by TFM do not update. Using the latest PMDG 777, Prepar3d 4.5.

**Comment by ajborka** [comment]
Will look into this. Is the APU running when you checked this, or are you at a complete cold/dark state?

**Comment by trodick** [comment]
This happens when completely cold and dark (loading 777 CLDDRK panel state) or while the APU is running. Also happens when engines are started (i.e., from FSFO Pro starting them). Slight aside, but will the panels be implemented in TFM like they are for the 737 and 747 at some point down the road? Thanks for looking into this.

**Comment by ajborka** [comment]
This is not confirmed for the 777-200LR using P3D5. When I tried at idle, the reading is N1: 20, N2: 15, burn rate 5192LBS/hour. When completely shut down, everything reads 0, although I had to give it time to completely shut down. When the APU is running, N1:5, N2:15, burn rate: 100LBS/hour. On the panels note, they will come in later builds.
