### ISSUE TITLE
bug: t f m gives error when triggering the right bracket key

### ISSUE THREAD

**Issue by jessieppp** [jfayre/talking-flight-monitor-net#11]
**Describe the bug**
T f m will give an error when hitting the right bracket key.

when the right bracket key is pressed the t f m app will show a dialog box with a continue, quit, and details buttons.  the app will put the following error: Hot key is already registered. (Exception from HRESULT: 0x80070581).  this bug will not let the program function properly.

**To Reproduce**

1. start flight sim and load in to a plain
2. open t f m.
3. while in t f m press the right bracket key.
4. the error will appear.

**Expected behavior**

expected for t f m to not error out and show me the information i was requesting.
**additional information
 - OS: [e.g. Windows 10]
Version 2004 (OS Build 19041.450)
 - TFM version: 
t f m ver pre 54

 - Flight simulator in use: 
prepar 3 d ver 4.5

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
ideal flight.

**Comment by jfayre** [comment]
This is now fixed in the latest build. This was some old test code I left in.
