### ISSUE TITLE
nothing logging to the speech output read only edit field.

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#18]
so I've been running a flight from Boston to phoenix using this new adderation of tfm, and not a thing is being logged to the speech output read only edit box.
Is this by design or has nothing been hooked up to the log to that edit field, or have I stumbled on something broken.

**Comment by ajborka** [comment]
It is not hooked up to any code yet. We are working on the issue, but was delayed in favor of a few other issues. Will be looking into it soon though.
