### ISSUE TITLE
bug: call outs don't appear to consistently fire when they should.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#22]
**Describe the bug**

call outs don't appear to fire when they should. This might be random, so I think I'll keep an eye on this. I have no logs to upload as I can't find them.

**To Reproduce**

1. launch tfm
2. start a descent, in my case it was a descent.
3. listen for the 25 hundred, 1000 etc.

**Expected behavior**

I expected to hear the 25 hundred, 1000, etc. I heard nothing and had to quickly switch back to the old tfm.

**additional information

windows 10 1909

 - TFM version: pre 0.66
 - Flight simulator in use: prepar3d version 4

**Additional context**

I was running at the time:

* ideal flight version preview 30 
* active sky
* fs tramp 8.40 
* sim toolkit pro version 6.29 at the time of this writing
* fs airlines,

**Comment by jfayre** [comment]
This is not implemented yet. He will get read out every 1000 feet, but the announcements you’re talking about haven’t been added yet.

**Comment by marrie** [comment]
Ah ok. I misunderstood then what was said. I'll leave the bug open 
though as kind of a check list item.

**Comment by jfayre** [comment]
GPWS callouts have now been added.
