### ISSUE TITLE
bug: tfm does not complete the destination when hitting right bracket plus d.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#28]
**Describe the bug**

Right bracket d appears not to say the icao of where I am headed

**To Reproduce**

1. launch tfm
2. go into the sim.
3. hit right bracket  then d
4. you will hear "time in route to ... [time] for example "time in route to ... 2 hours 30 minutes"

**Expected behavior**
I expected to hear "time in route to [insert icao code]

**additional information
windows 10 1909
 - TFM version: tfm version pre 0.69
 - Flight simulator in use: prepar 3d v4.5

**Additional context**

add ons:

* ideal flight version preview 30
* fs airlines
* sim toolkit pro (version 6.31
* fs tramp
* active sky

**Comment by jfayre** [comment]
I’ve been seeing this as well. This could be an FSUIPC bug. I’ll investigate.

**Comment by jfayre** [comment]
In looking back at the old TFM python source. I remembered I removed announcement of destination ICAO since it didn't work. I also removed it from the new TFM until we figure out what's up. Once we take over the flight plan stuff, this will be easy to add back in.

**Comment by marrie** [comment]
I like the time in route to  destination, this bug appears to be resolved. Thanks so much for a speedy fix.
