### ISSUE TITLE
bug: 0 minute isn't spoken when checking ETA to destination

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#29]
**Describe the bug**

when 1 hour 0 minutes  is encoutered when hitting right bracket (tfm) d, the 0 is not spoken
**To Reproduce**

1. launch tfm.
2. launch the sim.
3. start to fly as nromal.
4. when you see 1 hour 0 minutes x seconds you will here "1 hour ... minutes 50 seconds" for example.

**Expected behavior**
I should hear "1 hour 0 minutes 50 seconds" or "1 hour 50 seconds."

**additional information
 - OS: [e.g. Windows 10]windows 10 1909
 - TFM version:  tfm version pre 0.69
 - Flight simulator in use: prepar3dv4.5

**Additional context**
n/a

**Comment by marrie** [comment]
I can actually extend this issue to the 0 hour. I have about 54 minutes  ETA, and I heard " time in route to ... hours 54 minutes It's as if the blank items are beeing read, not the non blank items.

**Comment by ajborka** [comment]
Confirmed. The next waypoint [w should be checked for the same problem.

**Comment by marrie** [comment]
My pc is beeing a bit of a goof,  but I think it works, I'll verify this 
perhaps today or tomorrow.
