### ISSUE TITLE
bug:  door open and closed anouncement are in reverse

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#30]
**Describe the bug**

I hear doors are open when I shut them
**To Reproduce**
1. launch the sim.
2. launch TFM.
3. hit the key stroke for opening and closing doors. They will be opposite.

**Expected behavior**
I should hear "doors open" and "doors closed" when they are open and closed, not closed and open.

**additional information
 - OS: [e.g. Windows 10]windows 10 1909
 - TFM version:  tfm pre0.70
 - Flight simulator in use: prepar3dv4

**Additional context**

**Comment by jfayre** [comment]
Woops! This is fixed now and will be in the next build.
