### ISSUE TITLE
bug:  ground speed seems to be unable to keep up with a takeoff role.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#31]
**Describe the bug**

ground speed seems to be behind, or misleading I can't really describe the bug any other way.

**To Reproduce**

1. launch the sim.
2. launch tFM
3. start your pushback or take off role
4. Notice that the ground speed is way behind what you see in indicated. I saw 28 kts when I was going about 60. I can maybe splice the video where that happened later if necessary.

**Expected behavior**
the ground speed should be able to keep up with what I'm doing.

**additional information
 - OS: [e.g. Windows 10]windows 10 1909
 - TFM version:  tfm version pre0.71
 - Flight simulator in use: prepar3d

**Additional context**
n/a

**Comment by stickbear2015** [comment]
I can reproduce this on this end.

**Comment by marrie** [comment]
Can you test landing? I'll be landing in a few minutes, but I think I did notice even the landing didn't quite keep up either.

**Comment by jfayre** [comment]
I’ve seen this as well. Just haven’t got around to fixing it. 

Thanks for filing this.
