### ISSUE TITLE
repeated announcing of number (insert engine number) off/on during startup sequence.

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#32]
Hello,
I'm not really sure what's causing this, and it doesn't look to be plane specific.
In my case I
1. loaded up the TDS737-800
2. fired up the engines with ctrl+e
Expected behavior
You should be told once per change, I.E. engine 1 (status)
what actually happens
you get repeated notifications about engine/startup changes.
other notes
I can record this if necessary to provide better context.

**Comment by stickbear2015** [comment]
I've recorded a better demo of the issue.
you can download it with this link, I never said this was a professional recording.
https://www.dropbox.com/s/9pi5wl05y8pecyh/tfm-net-bug-recording.flac?dl=1
I do note in the recording that further checking looks like it's aircraft specific, but this issue never happened in the python release.

**Comment by jfayre** [comment]
Thanks. This helps.

I’ll load up the tds and see if I see this issue. The speed at which tfm checks for offset changes is quite a bit faster than in the python version, so it is possible the ignition offset is flickering on and off for a second or so.

**Comment by marrie** [comment]
this might be maybe due to the plane. Some of my planes do this and some do not. I've seen this even in my smart cars. Something to at least chew on.

**Comment by marrie** [comment]
I'm using version 89 and don't get this, or at least I don't think I do. Is this happening for the original poster as well? Or rather does it seem to be fixed?￼

**Comment by stickbear2015** [comment]
It's still happening with latest TFM build, but only with the TDS plane I use when a 737-800 is required.

**Comment by marrie** [comment]
I'll have to test with mine at some point, assuming I find something on 
one of my VAs, unless someone beats me to it. Is there a log output you 
can look at in the interim?
