### ISSUE TITLE
bug: Automatic announcement of next waypoint reports incorrect information

### ISSUE THREAD

**Issue by ajborka** [jfayre/talking-flight-monitor-net#34]
**Describe the bug**
When arriving at a waypoint, and TFM announces the next one, the announcement always announces the 3 mile transition instead of the next waypoint.

**To Reproduce**
1. Start a flight.
2. Start TFM
3. Wait until you reach a waypoint.

**Expected behavior**
TFM announces the waypoint, not the 3 mile transition period between waypoints.

**Comment by jfayre** [comment]
Hi,

I’m a bit confused on this. Are you saying the distances or wrong or the actual waypoint name is wrong?

**Comment by ajborka** [comment]
For example, the announcement reads: "Next waypoint: ght, distance 3 miles, bearing 254, time remaining: 00 hours, 00 minutes, 24 seconds" When it should have read "next waypoint: ght, distance 136 miles, bearing 254, time left: 19 minutes, 10 seconds."
