### ISSUE TITLE
bug:  some waypoint distances on first load  say "distance 3nm.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#38]
**Describe the bug**

IN some cases I will hear "way point name" distance 3nm
 when in most cases it is off by a lot, in some cases about 100 nm

**To Reproduce**

1. launch the sim.
2. launch tfm. Now load a flight into tramp.
3. start a flight.
4. keep an eye on the way point distance. I'm not sure if it is one of my add ons doing this when the next way point loads.

**Expected behavior**

I should hear the correct distance, and not 3 nm when the way point is announced.

**additional information
 - OS: [e.g. Windows 10]windows 10 1909
 - TFM version:  pre 0.78
 - Flight simulator in use: prepar 3d v4.5

**Additional context**

add ons:

1. ideal flight
2. sim sounds
3 fs airlines in this case (but this happens with any acars
4. sim toolkit version 6.32
5. fs tramp version 8.40
6. active sky

I can actually regress this way back to pre version 5.x if memory serves me correctly.

**Comment by jfayre** [comment]
This is a duplicate issue.
