### ISSUE TITLE
bug:  when replacing the files after a new update, the error that a geo names is not set comes up, even though you already put it in settings.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#40]
**Describe the bug**
when first starting tfm after replacing the files, you will get an error saying the geo names username is not set. This is false, as if you go to settings, you will find said username.

**To Reproduce**

1. unzip the tfm test into your testing folder, what ever that is.
2. replace all files in the folder.
3. launch tfm and notice the error.

**Expected behavior**
I should not get the geo names error.

**additional information
 - OS: [e.g. Windows 10] windows 10 1909
 - TFM version: tfm pre0.87
 - Flight simulator in use: prepar3d v4.5

**Additional context**
n/a

**Comment by jfayre** [comment]
This is interesting, because I’m not seeing this exact behavior. 

Try installing build 88, which was just posted and let me know if that’s any different.

**Comment by stickbear2015** [comment]
I literally just tried it here, and I'm not seing this.
I even tried completely deleting my TFM-test dir, and unzipping and my settings were still preserved, sooo I'm not sure.

**Comment by jfayre** [comment]
Just curious, did you unzip it into a folder with the same name? If I do, then it preserves settings now after a change I made this morning. Different folder doesn’t.

**Comment by stickbear2015** [comment]
I did, yes. but as soon as I get home from errands, I'll retest with what was just released.
note: I'm a nerd and compile from source, so all my info may be not so useful, lol.

**Comment by marrie** [comment]
I forgot to add, the error never happens again after relaunching. We'll 
see what happens with the next update when and if I have the time to 
test tomorrow.

**Comment by jfayre** [comment]
This is fixed.
