### ISSUE TITLE
suggestion: add a flaps key to announce,, if possible, your flap's position.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#41]
# use case:
A simmer is on descent and forgets what flaps position, if any, they are at.

# the idea
the user could hit a key, what ever that would be, to know what position, or percentage, or degrees they are at in terms of flaps the flaps position  could read as follows.

* if the user chose maybe in settings position, it would read "flaps 10."
* if the end user has the setting set to percent, it would read as such.
* ditto for degrees.

**Comment by jfayre** [comment]
That’s definitely workable. 

Right now, the number you get when adjusting the flaps is the angle in degrees. Would the position number also be helpful on this info key?

**Comment by marrie** [comment]
I personally use simple degrees such as 1, 5, 8, ETC. So, for me, the simple degrees would work.

**Comment by ajborka** [comment]
Both would be nice. Depending on what airplane manual you read, or directions you take from someone, they can use flaps 1, 3, 5, or 10. Others might use 10, 15, 28, 32. Some of it also depends on the developer of the plane.

**Comment by jfayre** [comment]
In the next build, right bracket, l, will read your flap angle. Flap handle position is a bit tricky, but it looks like I can get it.
I will add that later.
