### ISSUE TITLE
possible bug: using sapi to read groundspeed and ils

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#43]
Prior versions of tfm have a checkbox to have groundspeed, and ILS, read via sapi to reduce the info spoken by the screenreader at important times in the flight. There is a checkbox for sapi usage, but checking it does not yet change the speech output.

**Comment by jfayre** [comment]
Just want to check that this is now resolved. It should be.

**Comment by blindflightsimmer** [comment]
It is thanks
