### ISSUE TITLE
Suggestion: Mute SimConnect Messages should probably be mapped to Shift+R by default

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor-net#45]
Currently, the hotkey to mute SimConnect messages is Shift+M, but the key to speak the most recent SimConnect message is R.

For better consistency and to make it easier to memorize the mute shortcut, I suggest remapping this to a default key combo of Shift+R.

**Comment by marrie** [comment]
I plus 1 this. I already got myself into trouble as I was unaware the keystroke changed.  Can this be reverted back to TFM plus shift R? .

**Comment by jfayre** [comment]
This has been completed.
