### ISSUE TITLE
suggestion: specify direction to turn when entering a heading. 

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#48]
Once we have control of flight planning, etc. we should be able to specify what way to turn if necessary, I.E. if the controller says turn left heading 1 8 0, then we should be able to enter the heading then specify either by putting a letter in the box, I.E. l180 would be turn left 180, R360 would be turnn right 360, , or by selecting the direction in a combo box or by checking a box.
If you don't specify a direction, then TFM will simply pick the direction that is closest for your turn to the heading you enter.

**Comment by ajborka** [comment]
We might look into this at some point, but it isn't a high priority right now.
