### ISSUE TITLE
bug: locations don't report gates.

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#50]
**Describe the bug**
ref: commit ca1534302fe6d56e490f6a3fa6c46fad067522a0
When you query for a location when parked at a gate, you are only told on taxiway at (insert airport)
**To Reproduce**
Launch the sim, set up a flight, park yourself at a gate. (making sure you select a gate when setting your location.
Press the location key.
**Expected behavior**
you should hear at gate (insert gate numbe) at (airport name)
**actual behavior**
you hear on taxiway at (airport name)
**additional information**
- OS: windows 10.
 - TFM version: latest source as of this bug report
 - Flight simulator in use: FSX:SE

**Comment by jfayre** [comment]
This could be due to issues with the data for a particular airport.

Which airport and gate were you at?

**Comment by stickbear2015** [comment]
Jason,
I've only been at atlanta, and lax the past couple of days.
question: do I need to run make runways? Where does TFM pull it's info from for this feature?

**Comment by jfayre** [comment]
Yes. The FSUIPC .net dll pulls the data from the files generated by makerwys. The data files will be put in your sim folder. You don’t need to move them anywhere.

You will hear a message when tfm starts if the database loaded or not.

**Comment by ajborka** [comment]
Also keep in mind that some gates/taxiways don't have a name. In this case, you will hear "gate@]airport code]".

**Comment by stickbear2015** [comment]
I just re-ran make runways before bed last night so I'll play with it.

**Comment by stickbear2015** [comment]
I'm reopening this issue, with some more details.
I'm currently on the ground at KLAX, at gate 207.
When I push command key then shift+C I get taxiway at klax.
note: I am getting a successful database load message from TFM.
note 2: I have ran make runways before posting this.

**Comment by stickbear2015** [comment]
as a confirmation, I am hearing runway notifications as I took off frmo runway 25, and command key then shift+c did report runway 25l at klax.

**Comment by jfayre** [comment]
We’ll investigate this a bit more. I’ll make sure that gate is named in the database. It’s possible the code is flagging taxi ways when you’re also at a gate.

**Comment by jfayre** [comment]
It turns out that gates may overlap taxi ways in the database. I added a check to see if you are at a gate when it also thinks your on a taxi way. If so, the gate gets read. In this case, the taxi way name was blank anyway.

Not closing this just yet. Test it and let me know. It now works at the particular gate you mentioned. This is in build 105 which was just posted.

**Comment by stickbear2015** [comment]
I’m in the middle of a flight, I’ll give it a spin when I’m next on the ground and report back to this issue.

It’ll be a few hours as I’m doing a coast to coast from LA to Boston.

**Comment by stickbear2015** [comment]
commit fee63bdda87b939ea414bee01780de9e7738750b resolves the issue in question, This issue can now be closed. 👍
