### ISSUE TITLE
bug: smoking signs; do not read toggled.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#52]
**Describe the bug**

When triggering the hotkey for the "smoke system" in the sim, TFM of will not let you know if it is on or off. **To Reproduce**

1. Launch the sim. 
2. launch TFM.
3. If and only if a key is mapped to the smoke system, trigger it. otherwise, map it and come back to this step to trigger it. **Expected behavior**

I should hear a ding from the sim ′not sure about that one′ but I should
 hear TFM indicate if the signs are on or off. 

**additional information
 - OS: [e.g. Windows 10] Windows 10 1909. 
 - TFM version: TFM version pree 0104
 - Flight simulator in use: Prepar v4.5

**Additional context**
N/a.

**Comment by jfayre** [comment]
I’ll look, but I think Smoke System and No Smoking signs are two different controls.

**Comment by jfayre** [comment]
Smoke system is a different control. The one you want is: Cabin alert - No Smoking (on/off)

**Comment by marrie** [comment]
I'll have to look. I was actually trying to troubleshoot this last night 
with someone, and myself actually. I typed "smoke" and that's the only 
thign I found in prepar3d version 4.5. The other sign I mapped reads 
fine.
