### ISSUE TITLE
Suggestion: have the sapi speech be interrupted

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#54]
Basically, the suggestion stems  from the fact that I could be let's say landing or what not, and I hear ground speeds that are way behind what they should be, or I'm taking off ground speeds are read, I rotate, and I hear ideal flight say I'm off the ground, TFM takes a while as the last ground speed is still being spoken. 

A delay in interruption would I think be handy. If not, we can probably come up with another solution.

**Comment by jfayre** [comment]
I need a bit more info here. I can fairly easily flush the SAPI speech once you are airborn, but are you looking for other speech events to be interrupted as well?

**Comment by marrie** [comment]
Sort of. When I'm on the ground and land, at least for me the speeds are 
a bit behind. I was actually stoppped and it took a while for the speach 
part to get to 0 kts. On take off, it's fine, or at least, seems fine.

**Comment by jfayre** [comment]
I’ll take a look. Ground speed is on a 3 second timer right now.

**Comment by marrie** [comment]
That's probably workable, but because of the slow rate of speech I hear 
150, pause for about 5 seconds, 130 when on my instrument  panel it says 
about 80 , etc. Maybe it's 3 seconds, I don't know. I will also keep an 
eye on this.

**Comment by jfayre** [comment]
You can now adjust the sapi speech rate in Settings.

**Comment by marrie** [comment]
I will have a play with this. Can we also in time adjust the   time 
between messages, from what not to what not seconds? So let's say 1 
second to 5? Or even 0.5 seconds to 5 seconds? If not, then in the 
future.  The delay between messages right now is not a big  deal in the 
big picture.
