### ISSUE TITLE
requesting cities someitmes no output

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#56]
when i hit right bracket c, sometimes it wont say anything at all.

**Comment by trodick** [comment]
@BviPilots This is particularly true if you are in an area where Geonames literally has no city information it can give you, i.e., in the middle of the ocean, or in a remote part of the world that has no nearby towns within a certain radius. I would suggest that we come up with a message, such as "No nearby city," in cases like this.

**Comment by marrie** [comment]
I cannot reproduce this issue. What are steps to reproduce? what add ons are you using etc? what sim are you using?
