### ISSUE TITLE
Feature Request: fuel manager

### ISSUE THREAD

**Issue by Orinks** [jfayre/talking-flight-monitor-net#57]
Create a fuel manager within TFM to accessibly add fuel to anyaircraft regardless of sim.

Objectives:

-  A dialog or tab within TFM to enter given amount of block fuel in pounds or, optionally, killagrams.
-  If the block fuel value exceeds the maximum fuel weight of the aircraft, issue a warning about being overfueled.

This should help fuel an aircraft regardless of sim platform.

**Comment by jfayre** [comment]
This shouldn't be all that hard to do. 
Can you reply with a quick note about how fuel is normally distributed in the tanks? I know center tanks get filled first, but not sure what typically goes after that, especially for very large aircraft. I'm picturing an edit control where you can enter block fuel, as well as controls for each tank on the aircraft.

**Comment by Orinks** [comment]
Depends on the aircraft. Research outboard fueling for a general idea.
Generally the bottom/wing tanks first, then the mains, and then the
one or two center tanks.
