### ISSUE TITLE
bug: control shift I does not work to open the submit issue page.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#6]
# steps

1. launch TFM.
2. hit alt to go to the menu bar.
3. navigate to the help area and press down arrow.
4. navigate to the submit issue prompt.

# expected

 Control shift I should open the submit issue page.

# actual
nothing seems to happen in my case. I remain at the tab where I was last. in my case the avionics tab

# tfm build 
0.39

I can't really regress this yet, as this is my first time using the new TFM

**Comment by ajborka** [comment]
Fixed with the newest build. Also see issue #9 .
