### ISSUE TITLE
request: remove values in field when editing autopilot 

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#62]
Currently, when hitting shift and a key to edit a value, the field is filled with the current autopilot value. Since hitting s tells us what the current value is anyway, it would make things quicker to remove the value so we are presented with a blank field. Or have the text remove as soon as we start typing. Whatever is easier.

**Comment by marrie** [comment]
I think removing the value when you start typing would actually be easier, if that is in fact easier. This would serve as a reminder to the end user what that value was, or at least let them know they are in that field.

**Comment by jfayre** [comment]
This will be corrected in the next build. I have set the text in the box to be selected when the dialog opens, so you can just type over it.
