### ISSUE TITLE
bug: showing plains in the sky

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#64]
When i hit right bracket p it gives me the following message with the microsoft framework error 
NHotkey.HotkeyAlreadyRegisteredException: Hot key is already registered. (Exception from HRESULT: 0x80070581) ---> System.Runtime.InteropServices.COMException: Hot key is already registered. (Exception from HRESULT: 0x80070581)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.

**Comment by jfayre** [comment]
That’s odd. I’m not seeing that here. Are you sure you don’t have another instance of TFM running?

**Comment by jfayre** [comment]
Ok, I think I see what’s going on.

If you press left bracket for the autopilot keys, then don’t press one of those keys, but instead press Right bracket, it throws an error. I’ll fix this.
