### ISSUE TITLE
tfm reporting too many fuel tanks

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#65]
getting too many tanks reporting when i use the right bracket 1 through 9. THis is happening in the tripple 7 300

**Comment by jfayre** [comment]
Hi,

I need a bit more details. Is it reporting tanks that aren’t there? If it’s only this aircraft having the issue, it could be something odd with the configuration of the aircraft.

If it’s this aircraft specifically, can you send me a link to it? I don’t think I have the 777.

**Comment by jfayre** [comment]
this was fixed quite a while ago.
