### ISSUE TITLE
Feature Request: Auto-calculation of cargo/payload

### ISSUE THREAD

**Issue by Orinks** [jfayre/talking-flight-monitor-net#68]
Since a "payload" tab exists in the TFM fuel and payload manager, it would only make sense to be able to add our given SimBrief payload as well, similar to block fuel.

**Comment by jfayre** [comment]
I can ask Paul about it, but how would you picture that being done. It seems like most aircraft have different terminology for the payload stations. Baggage isn’t always called Baggage, etc.

If we can come up with a specific recommendation, I’m happy to ask.

**Comment by stickbear2015** [comment]
the other issue we're dealing with is sometimes passengers need to be set right, etc. their's a lot to be considered for that tab. :)

**Comment by jfayre** [comment]
I took a quick look at how Ideal Flight loads payload when you enter a weight in the flight generator.

It seems to start at the front of the aircraft, then just keep adding payload until the weight you entered. It doesn’t take any consideration for balance. When I tested it, it put 3000 pounds total in the front few load stations, and left all the others empty.

**Comment by Orinks** [comment]
Ah, I see. That might be why sometimes it gets fuel wrong then.
