### ISSUE TITLE
bug:  system tray setting doesn't stick on restarts of TFM

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#69]
**Describe the bug**

When restarting TFM, the setting to go to systray doesn't stick. 

**To Reproduce**

1. Launch the sym. This might not be necessary. 
2. Launch TFM.
3. invoke settings from the menu bar.
4. Once the settings tree gains focus, hit end to go to user interface. 
5. tab to, and check the hid to system tray box. 
 minimize TFM. 
7. restart TFM and invoke the settings section.
8. hint end to go to the user interface.

The check box which the end user checked is no longer checked. 

**Expected behavior**

The box should remain persistent throughout restarts. 

**additional information
 - OS: [e.g. Windows 10] 1909
 - TFM version:  pre132
 - Flight simulator in use:  preparv4.5

**Additional context**
N/A

**Comment by jfayre** [comment]
assigning this to Andy.

**Comment by ajborka** [comment]
@marrie  you have to press the OK button to save the settings. Just checking the box isn't going to make it stick. Keep in mind that TFM won't start in the system tray, only when you minimize it.
