### ISSUE TITLE
bug: I hear blank every 5 or so minutes while TFM is launched.

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#7]
# steps:
1. launch TFM.
2. launch the sim and flight plan. This could be going anywhere, but in my case I was going from KLAS to KLAX.
3. wait and every 5 minutes or so, you hear "blank." I'm assuming it is trying to read from geo names. is this a placeholder?

# expected
I should not be hearing "blank" I should be hearing the closest city if this is indeed what is going on.

# actual
I  hear my screen reader, NvDA in this case, say "blank." I can check the nearest city though with right bracket  C.

**Comment by marrie** [comment]
This is still happening in version 0.66. The add ons I can remember are 

* ideal flight
*sim tool kit
* active sky
*fs tramp
*fs airlines (but this was doing the behavior before fs airlines).
* gsx (I don't run that but it is installed)


Out of all of those add ons I can't really think of what could be making the add on say "blank" every 3-5 minutes. Active sky is reading fine, everything as far as I know is reading in the sim connect window including most of the way points ideal flight announces.
I know of one other person who is having said issue, but I'll let them submit a comment in case their add ons are different than mine.

**Comment by marrie** [comment]
I can still reproduce this in version pre 0.69. add ons are the same. I cannot find logs, so cannot upload any.

**Comment by jfayre** [comment]
I just pushed a new build that adds logging of simconnect messages.

Can you run the latest one, and then send me the tfm.log file that will be in the same directory as the executable? Send me the log after you get the blank message.

**Comment by marrie** [comment]
Got the log per the request in the discord, I hope? I mean I hope it is the right file.
[tfm.log](https://github.com/jfayre/talking-flight-monitor-net/files/5197768/tfm.log)

thanks.

**Comment by marrie** [comment]
Looks like this for now is solved in the interim. Thanks.
