### ISSUE TITLE
Fuel reading double read out

### ISSUE THREAD

**Issue by BviPilots** [jfayre/talking-flight-monitor-net#70]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.
When you hit right bracket followed by the number, if you have for example 3 tanks, it will show the tanks twice so when you do right bracket 1 through 3, you can also hit right bracket 3, 5, and 6 and it  reads the same tanks again.

**Comment by jfayre** [comment]
That’s very odd. Which aircraft were you flying. Has this behavior changed in recent versions?

**Comment by marrie** [comment]
I don't think I can reproduce this. I've been flying the 737 and see Rj and Airbus a 320 Neo and I don't get a double read out of fuel.￼ actually, how is this even reproduced? Unless I missed it, I did not see any way to reproduce this. I can take a look at the next time I fly which should be some point this week.￼

**Comment by jfayre** [comment]
Cannot reproduce.
