### ISSUE TITLE
left bracket key reports hotkey error in ap_Set_Transponder

### ISSUE THREAD

**Issue by stickbear2015** [jfayre/talking-flight-monitor-net#73]
Every time I push the left bracket key, I get the following
hotkey error in ap_Set_Transponder

**Comment by trodick** [comment]
That really isn’t helpful without any version context. Are you using the latest snapshot or the latest source version (if so, what branch and what commit hash)?

From: Shane Popplestone
Sent: Sunday, November 8, 2020 3:44 PM
To: jfayre/talking-flight-monitor-net
Cc: Subscribed
Subject: [jfayre/talking-flight-monitor-net] left bracket key reports hotkeyerror in ap_Set_Transponder (#73)

Every time I push the left bracket key, I get the following
hotkey error in ap_Set_Transponder

**Comment by stickbear2015** [comment]
that's what happens when copy and paste fails.
lol.
It's the latest source commit based on branch master.

**Comment by trodick** [comment]
Any other errors thrown (if you can, give us a stack trace, please?)

**Comment by stickbear2015** [comment]
@trodick no stack traces that I can see, and it's not logging to a log file, I'm on discord if we want to see about pulling  together a stack trace we can log here.

**Comment by ajborka** [comment]
Let me look into this. It sounds like there is a missing break statement in the switch statement that controls the AP set value window.

**Comment by ajborka** [comment]
Running the latest master build doesn't give me this problem. We need more info about the problem. What simulator do you use? What did you press after the [ key? What other addons are you using when this happens? Feel free to reopen the issue when you can provide the required information.

**Comment by stickbear2015** [comment]
I'm using FSX:Steam, addons running, FS Tramp, fsx active sky, GSX, and AAVirtuals acars software.
The error is spoken right after pushing the left-bracket key.
As I run from compiled source  direct from master, I'll delete the copy I compiled and recompile and see if it goes away.
more when I have more to report.

**Comment by stickbear2015** [comment]
in the event this helps, here's the build output when I build using latest master branch with file source/tfm.sln
1>------ Build started: Project: tfm, Configuration: Debug Any CPU ------
1>C:\src\talking-flight-monitor\source\navigraph\navigraphContext.cs(49,10,49,214): warning CS1030: #warning: 'To protect potentially sensitive information in your connection string, you should move it out of source code. See http://go.microsoft.com/fwlink/?LinkId=723263 for guidance on storing connection strings.'
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(29,20,29,24): warning CS0168: The variable 'mods' is declared but never used
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(30,20,30,23): warning CS0168: The variable 'key' is declared but never used
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(38,20,38,24): warning CS0168: The variable 'mods' is declared but never used
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(39,20,39,23): warning CS0168: The variable 'key' is declared but never used
1>C:\src\talking-flight-monitor\source\TFMMainForm.cs(138,30,138,32): warning CS0168: The variable 'ex' is declared but never used
1>C:\src\talking-flight-monitor\source\TFMMainForm.cs(156,30,156,32): warning CS0168: The variable 'ex' is declared but never used
1>C:\src\talking-flight-monitor\source\TFMMainForm.cs(809,30,809,32): warning CS0168: The variable 'ex' is declared but never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(1080,69,1080,71): warning CS0168: The variable 'ex' is declared but never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(1121,73,1121,75): warning CS0168: The variable 'ex' is declared but never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(134,22,134,30): warning CS0169: The field 'IOSubsystem.onGround' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(217,22,217,35): warning CS0169: The field 'IOSubsystem.readNavRadios' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(131,22,131,37): warning CS0169: The field 'IOSubsystem.calloutsEnabled' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(90,25,90,31): warning CS0169: The field 'IOSubsystem.BankWG' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(215,24,215,34): warning CS0169: The field 'IOSubsystem.apAltitude' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(240,21,240,38): warning CS0169: The field 'IOSubsystem.waypointLoopCount' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(132,22,132,32): warning CS0169: The field 'IOSubsystem.ILSEnabled' is never used
1>C:\src\talking-flight-monitor\source\frmFuelManager.cs(20,49,20,60): warning CS0169: The field 'frmFuelManager.selectedKey' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(214,24,214,33): warning CS0169: The field 'IOSubsystem.apHeading' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(234,21,234,45): warning CS0169: The field 'IOSubsystem.RunwayGuidanceModeSelect' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(211,21,211,37): warning CS0649: Field 'IOSubsystem.OldSpoilersValue' is never assigned to, and will always have its default value 0
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(123,24,123,36): warning CS0169: The field 'IOSubsystem.nextWaypoint' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(141,22,141,43): warning CS0169: The field 'IOSubsystem.flightFollowingOnline' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(128,22,128,44): warning CS0169: The field 'IOSubsystem.FlightFollowingEnabled' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(72,34,72,50): warning CS0169: The field 'IOSubsystem.bankSineProvider' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(130,22,130,47): warning CS0169: The field 'IOSubsystem.SimConnectMessagesEnabled' is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(129,22,129,44): warning CS0649: Field 'IOSubsystem.InstrumentationEnabled' is never assigned to, and will always have its default value false
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(18,22,18,35): warning CS0414: The field 'frmKeyboardManager.apTabSelected' is assigned but its value is never used
1>C:\src\talking-flight-monitor\source\IOSubsystem.cs(137,22,137,34): warning CS0414: The field 'IOSubsystem.flapsEnabled' is assigned but its value is never used
1>C:\src\talking-flight-monitor\source\Keyboard manager\frmKeyboardManager.cs(19,22,19,40): warning CS0414: The field 'frmKeyboardManager.generalTabSelected' is assigned but its value is never used
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========

**Comment by stickbear2015** [comment]
a recompile from source after deleting my bin directory still produces the error in question right after hitting the left-bracket key.

**Comment by jfayre** [comment]
I’m seeing this as well. I think it might be a duplicate key with the new throttle percentage code. I’ll look.

**Comment by ajborka** [comment]
I never see this, so it must be an FSX only problem/. Then again, I never tried setting throttle values.
