### ISSUE TITLE
feature request: add adjustable speed brakes dialogue 

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#76]
Currently, we can hit slash to go to 100 per cent speed brakes. However, often you only need a little speed brake to help with slowing down and 100 per cent causes the aircraft to go crazy trying to maintain speed. Unfortunately, there is no way to assign a key to adjust the speed brake per centage. Is this definable with FSUIPC so that we could enter values for speed brakes like we have for the throttles.

**Comment by ajborka** [comment]
@blindflightsimmer  I will look into it this weekend and get back to you.

**Comment by trodick** [comment]
@ajborka I'll handle this, shouldn't be too difficult, so you can keep working on the flight planner. Will submit a PR when it's done.

**Comment by blindflightsimmer** [comment]
any news on this feature?

**Comment by jfayre** [comment]
Tyler was going to do this. If he isn’t able to get to it soon, I’ll do it.

**Comment by ajborka** [comment]
Closing since freeware planes have this now. We have it on the list of things to do for the PMDG.
