### ISSUE TITLE
suggestion: left and right heading directions

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#8]
# situation 

vatsim or you ATC  tells you "turn left heading 270.

# solution 

what you could do in the box is this.

* if nothing is entered, choose the shortest way to the heading.
* if l is entered along with the heading, turn left. EG, l370
* if r is entered along with the heading,  turn right. EG, r270

I was going to suggest radio buttons, but I think the quickest way would probably be the text field idea. I'm kind of getting the idea from FSXPilot

**Comment by marrie** [comment]
adding to this, instead of l and r which could be an option could plus minus be used as well, plus beeing right minus beeing left? so -250, "turn right to heading 250" and -75 "turn left to heading 75," if nothing is entered, find the quickest way there to said heading.

**Comment by jfayre** [comment]
On the sim end, this could be done by slowly incrementing or decrementing the heading bug. Right now, when you plug in a heading, we just send that value directly to the sim. I’m not sure how the sim determines which way to turn. I think it probably just turns in whichever direction is fastest to get to the particular heading.

**Comment by marrie** [comment]
Sure does. I would want if possible a faster  way of doing this in case 
the bug is too slow.  If we do use the heading bug which I've never 
used, I've used the other bugs,  can tfm announce  heading blah blah 
blah assuming the l r or plus minus can't be implemented as of yet?

**Comment by ajborka** [comment]
Part of this requires a logic change in the user interface. It can be done though. Right now, the autopilot changes the heading bug whether we send a value or it gets one from somewhere else. Since the plane can only bank at a maximum rate defined by the manufacturer, say 25 degrees, it takes time for the plane to turn to course. EX: If you were flying at heading 0, and the plane had a max bank of 25, it means that the plane can turn a maximum of 25 degrees every 10-20 seconds. To be safe, give it around a minute under normal conditions. The autopilot does choose the fastest turn to heading. However, there may be instances where you might need to take the longer way around the turn.

**Comment by marrie** [comment]
Fair point. So if vatsim or posan or what ever we are using says "turn 
left heading 180" we can for now use the bug even though it will in fact 
be slower, assuming we have to take the long way around? I would like 
l/r, or what not, but the bug I guess will have to do for now.

**Comment by ajborka** [comment]
If they told you to turn 180 left, and you were headed to 0, you could tell FSTramp to head to 180. In the event they told you to turn 80 left, and you were at 300, then put 220 into FSTramp. The simple formula is + for a right turn and - for a left turn. EX: If you were headed to 300, an 80 degree left turn is -80 (220), and an 80 degree right turn (+80) would be 020).

**Comment by marrie** [comment]
Makes sense, except that will be way too complicated to figure out on 
the fly. Plus i don't think that will work as if I put 220 and I'm told 
to turn left to heading 80, tramp or tfm will turn to heading 220 not 
80, unless I just got everything  backqord. Math is not my best subject. 
The offset does make sense though.

**Comment by ajborka** [comment]
Closing this because you can't tell autopilot what direction to turn when it is turned on. It will normally make the best choice between a left/right turn.

**Comment by marrie** [comment]
Makes sense. What I’ve done is baby sit and go 20 degrees at a time to 
make it easier.

Thanks.
