### ISSUE TITLE
Screen reader focus doesn't change in takeoff assist selection in settings

### ISSUE THREAD

**Issue by Orinks** [jfayre/talking-flight-monitor-net#80]
**Describe the bug**
When selecting a takeoff assist option, NVDA focus does not move with the cursor.
**To Reproduce**
Tools > settings > aircraft and select a takeoff assist mode.

**Expected behavior**
Screen reader moves along with the cursor selection.
**additional information
 - OS: [e.g. Windows 10]
 - TFM version: 
 - Flight simulator in use: 
- specific aircraft in use:

**Additional context**
Add any other context about the problem here. What other add-ons were you running at the time, etc.

**Comment by jfayre** [comment]
This is a known issue with combo boxes with NVDA and Windows Forms apps.

Andy, can we either implement the workaround for speaking the combo or just change this to a radio button?

**Comment by ajborka** [comment]
I will implement the fix for it. However, it might not make it in this weekend's build. Everything will depend on how much of the airports dialog is finished by then. Hoping to get it done today or early tomorrow.

**Comment by jfayre** [comment]
This appears to be fixed. Closing.
