### ISSUE TITLE
bug: When pressing H to check heading at low altitudes, TFM reports "true" and "magnetic" heading resulting in super verbose speech output

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor-net#84]
**Describe the bug**

When flying at low altitudes (up to 10000 FT) and pressing the TFM key followed by H to check the current heading, TFM reports a "true heading" and "magnetic heading".

This results in rather verbose speech output and can also be confusing for users who may be unsure what the difference between true and magnetic heading is, it also means it's more cumbersome to quickly check the current heading and report back to ATC, e.g. when flying a vectored departure.

I don't think there's a need for us to know the true vs magnetic heading difference in any situation, and so would recommend removing this info or allowing users to toggle this using a checkbox in settings.

**To Reproduce**

While flying at a low altitude below 10000 FT, press TFM key followed by H.

**Expected behavior**

TFM should report "Heading" followed by a value, e.g. "Heading 240".

**additional information
 - OS: Win 10
 - TFM version: 2.0 Alpha 3
 - Flight simulator in use: P3d v5

**Comment by jfayre** [comment]
Hi,

I can take this out. I mainly did this since I believe ILS course values are represented as True heading, so was using it for debugging.

**Comment by robin24** [comment]
Awesome, thanks Jason! 👍
