### ISSUE TITLE
Suggestion: Autopilot commands should include hotkeys to get / set altimeter

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor-net#85]
Currently, there are no hotkeys in TFM to get or set the altimeter value, the only way to do this is to navigate to either the Altimeter QNH or the Altimeter Inches gauge in the TFM main window.

It would be great if appropriate commands could be added to TFM's autopilot hotkeys, I suggest using the B key for this as there's no autopilot command currently associated with that key, and it's the key that P3d / FSX use by default to set the altimeter.

When the TFM Autopilot modifier key is pressed followed by B, TFM should speak the current altimeter setting (both QNH and inches).

When pressing the TFM Autopilot modifier followed by pressing Shift+B, a dialog should open allowing users to set a new value, there should be 2 tabs depending on whether the user wants to input the QNH or inch value.

Additionally, it would be super neat if a transition level could be specified, so that TFM will only apply the new altimeter setting when the specified altitude is reached.

**Comment by trodick** [comment]
Usually, transition level is something that the pilot pays attention to, and resets the altimeter manually upon passing through it.

**Comment by robin24** [comment]
I’m not sure, I’ve definitely watched videos of sighted sim pilots where they were setting the transition level somewhere on the instrument panel.

My assumption was that they did this so that the altimeter would automatically switch over when the specified altitude was reached, but I might be completely wrong about this :-).

Robin

**Comment by trodick** [comment]
Hi Robin,

In most cases where the transition level is set (PMDG 737 NGXu, for instance), it's set so that you get an annunciation telling you to switch to standard above the TL. Usually it's a color change of the altimeter display and the letters "STD" will show up somewhere.

Tyler

**Comment by ajborka** [comment]
Hi,

This is not possible with freeware aircraft because they automatically reset the altimeter at 18000 feet. Pressing b in the simulator should reset the altimeter though.
