### ISSUE TITLE
bug: "Altimeter Inches" gauge value does not contain decimal dot

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor-net#86]
**Describe the bug**

When selecting the "Altimeter Inches" gauge, the altimeter value is shown without the decimal dot (e.g. 2992 instead of 29.92).

This is true for both the combo box and text field where a new altimeter value can be entered, which is confusing as this way one would think that a new altimeter value should also be entered without the decimal dot, which isn't the case.

As an additional step, TFM should probably sanity check user input in the Altimeter Inches text field to ensure that a decimal value was entered, as currently that does not appear to be the case.

 - OS: Win 10
 - TFM version: 2.0 Alpha 3
 - Flight simulator in use: P3d v5

**Comment by ajborka** [comment]
At some point, we will remove the content from the main window, so we won't be doing any work on that part of the UI. We can take a look at the altimeter inches setting and see if it is a problem with FSUIPC or TFM.

**Comment by jfayre** [comment]
I will add a decimal to the UI, since it’s trivial.

I will also take this opportunity to add an altimeter setting dialog to the dialogs accessed directly from the sim. 

Andy is correct though, the main window UI will be removed at some point, so we will not be doing a lot of work on it.
