### ISSUE TITLE
bug: GPWS callouts are not repeated when descending through the same altitude more than once

### ISSUE THREAD

**Issue by robin24** [jfayre/talking-flight-monitor-net#87]
**Describe the bug**

GPWS callouts are not repeated when descending through the same altitude more than once.

**To Reproduce**

1. With any aircraft, perform an approach and descend below 1000 FT.

Result:

TFM plays the 2500 and 1000 FT callouts as expected.

2. Climb back up to 3000 FT and repeat the descent down to ground level.

Result:

TFM does not play the 2500 and 1000 FT GPWS callouts for the second descent, and only starts to play callouts after descending through 500 FT.

The callouts that had been played for 2500 and 1000 FT on the first descent are not repeated as expected.

This also happens when completing one flight and then doing a second flight in the same sim session, in which case no callouts are played for the second flight unless TFM is restarted.

**additional information
 - OS: Win 10
 - TFM version: 2.0 Alpha 3
 - Flight simulator in use: P3d v5

**Comment by marrie** [comment]
I've managed to reproduce this as well. I have a related bug with the call outs which I'll file later.
