### ISSUE TITLE
bug: excecuting the control shift w keystroke for opening up the web page is currently broken

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#9]
# summary
When the end user issues control shift w to bring up the web page, the hotkey listed in help does nothing.

# steps

1. launch TFM. (I don't know if launching the sim should be first as this has nothing to do with prepared)
2. tap alt
3. scroll right to help and press down arrow.
4. navigate to the  "open web page" prompt and notice the key stroke

# expected

I probably should be seeing the web page

# actual

nothing happens. This might be a place holder. See the bug I submitted about command shift I. I'm going to try and reference it here. If not, hence the note.

# regression

I can regress this to TFM version 0.38.

#6

**Comment by ajborka** [comment]
Fixed with the newest build.
