### ISSUE TITLE
bug:  hitting the TFM or AP key causes the call out to be interrupted

### ISSUE THREAD

**Issue by marrie** [jfayre/talking-flight-monitor-net#90]
**Describe the bug**

When you hear a call out and  you happen to hit TFM (right bracket) or AP (left bracket) the call out's speech will be interrupted.

**To Reproduce**

1. Launch TFM.
2. Launch the sim. (Reverse these steps if needed).
3. fly your plan as normal using tramp or what ever is used.
4. Start your descent as normal.
5. Notice when you hear "25 hundred" and you hit the TFM or AP keys the speech of the call out will be interrupted. I can regress this to about alpha 2.1.

**Expected behavior**

I expect the call out speech not to be interrupted when I hit right  or left bracket to check something.

**additional information
 - OS: [e.g. Windows 10] windows 10 2004h2
 - TFM version: 
2.0Alpha5 - 

Flight simulator in use:  prepar3d version 4.5
- specific aircraft in use: n/a. I can reproduce this in all the craft I fly.

**Additional context**
ideal flight, active sky, fstramp
,sim toolkit pro

**Comment by jfayre** [comment]
This will require reworking the audio system that we use to play the wav files. I will look into it. 

Just as a note to myself, look into using nAudio’s mixer feature, as we do for attitude indication tones.
