### ISSUE TITLE
audio system is broken

### ISSUE THREAD

**Issue by blindflightsimmer** [jfayre/talking-flight-monitor-net#93]
Can't place exactly when this happens, within 10 mins of having the program open normally or just after takeoff. The command key sounds disappear, as do gpws and attitude mode. Thinking this has something to do with the recent audio changes.

**Comment by jfayre** [comment]
I might have just found the issue.

When the audio stopped working, had you used Runway guidance mode? There was a bug when runway guidance turned off that would kill the audio mixer.
